```
[Title] Univariate LSTM
[Author] Jason Brownlee
[Etidor] Yibeck.Lee(yibeck.lee@gmail.com)
[reference]
 - https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/
```

In [1]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.


In [27]:
# split a univariate sequence into samples
from numpy import array
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		print(i)
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [30]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 4
n_features = 1
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

0
1
2
3
4
5
[10 20 30 40] 50
[20 30 40 50] 60
[30 40 50 60] 70
[40 50 60 70] 80
[50 60 70 80] 90


In [31]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [32]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
X = X.reshape((X.shape[0], X.shape[1], n_features)) #1,3,1
X

array([[[10],
        [20],
        [30],
        [40]],

       [[20],
        [30],
        [40],
        [50]],

       [[30],
        [40],
        [50],
        [60]],

       [[40],
        [50],
        [60],
        [70]],

       [[50],
        [60],
        [70],
        [80]]])

In [36]:
# fit model
model.fit(X, y, epochs=100, verbose=1) #log를 0 않씀 1 사용

Epoch 1/100
5/5 [==============================] - 0s 0us/step - loss: 5260.2354
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 5089.1729
Epoch 3/100
5/5 [==============================] - 0s 1ms/step - loss: 4923.6782
Epoch 4/100
5/5 [==============================] - 0s 1ms/step - loss: 4765.6499
Epoch 5/100
5/5 [==============================] - 0s 800us/step - loss: 4612.4829
Epoch 6/100
5/5 [==============================] - 0s 600us/step - loss: 4465.2866
Epoch 7/100
5/5 [==============================] - 0s 800us/step - loss: 4328.5122
Epoch 8/100
5/5 [==============================] - 0s 800us/step - loss: 4199.0425
Epoch 9/100
5/5 [==============================] - 0s 600us/step - loss: 4072.4165
Epoch 10/100
5/5 [==============================] - 0s 600us/step - loss: 3948.2949
Epoch 11/100
5/5 [==============================] - 0s 600us/step - loss: 3816.3804
Epoch 12/100
5/5 [==============================] - 0s 600us/step - loss: 3682.9636
Epoch 13/

In [37]:
# demonstrate prediction
x_input = array([70, 80, 90,100])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=1)

1/1 [==============================] - 0s 0us/step


In [38]:
x_input,yhat

(array([[[ 70],
         [ 80],
         [ 90],
         [100]]]), array([[111.9794]], dtype=float32))