```
[Title] Univariate LSTM
[Author] Yibeck.Lee(yibeck.lee@gmail.com)
[reference]
 - https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/
```

In [19]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [20]:
# split a univariate sequence into samples
from numpy import array
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [21]:
# univariate data preparation
from numpy import array
# define input sequence
import pandas as pd
df = pd.read_csv("MATERIAL_DEMAND_1.csv")
df
raw_seq = df[["TODAY_DEMAND"]][:720]
raw_seq = raw_seq.values
raw_seq
# choose a number of time steps
n_steps = 3
n_features = 1
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
#for i in range(len(X)):
#	print(X[i], y[i])

In [22]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [23]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
X = X.reshape((X.shape[0], X.shape[1], n_features))
#for i in range(len(X)):
#	print(X[i], y[i])

In [24]:
# fit model
model.fit(X, y, epochs=200, verbose=0)

In [25]:
# demonstrate prediction
x_input = array([2695, 2620, 2654])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=1)

1/1 [==============================] - 0s 217ms/step


In [26]:
yhat,(n_steps,n_features)

(array([[2669.6667]], dtype=float32), (3, 1))

In [12]:
raw_seq = df[["TODAY_DEMAND"]][720:]
x_input = array(raw_seq)
x_input


array([[2738],
       [2649],
       [2692],
       [2715],
       [2702],
       [2695],
       [2620],
       [2654],
       [2702],
       [2754],
       [2861],
       [2853],
       [2819],
       [2819],
       [2805]], dtype=int64)

In [13]:
X_test, y_test = split_sequence(x_input, n_steps)
for i in range(len(X_test)):
	print(X_test[i], y_test[i])

[[2738]
 [2649]
 [2692]] [2715]
[[2649]
 [2692]
 [2715]] [2702]
[[2692]
 [2715]
 [2702]] [2695]
[[2715]
 [2702]
 [2695]] [2620]
[[2702]
 [2695]
 [2620]] [2654]
[[2695]
 [2620]
 [2654]] [2702]
[[2620]
 [2654]
 [2702]] [2754]
[[2654]
 [2702]
 [2754]] [2861]
[[2702]
 [2754]
 [2861]] [2853]
[[2754]
 [2861]
 [2853]] [2819]
[[2861]
 [2853]
 [2819]] [2819]
[[2853]
 [2819]
 [2819]] [2805]


In [14]:
x_input = X_test[0].flatten()
x_input

array([2738, 2649, 2692], dtype=int64)

In [15]:
x_input = x_input.reshape((1, n_steps, n_features))
print(x_input)
yhat = model.predict(x_input, verbose=1)

[[[2738]
  [2649]
  [2692]]]
1/1 [==============================] - 0s 0us/step


In [16]:
yhat

array([[2723.9824]], dtype=float32)

In [17]:
y_pred = []
for i in range(len(X_test)):
    x_input = X_test[i].flatten()
    x_input = x_input.reshape((1, n_steps, n_features))
#     print(x_input)
    yhat = model.predict(x_input, verbose=1)
    print(x_input, yhat)
    y_pred.append(yhat[0][0])
y_pred

1/1 [==============================] - 0s 16ms/step
[[[2738]
  [2649]
  [2692]]] [[2723.9824]]
1/1 [==============================] - 0s 0us/step
[[[2649]
  [2692]
  [2715]]] [[2697.178]]
1/1 [==============================] - 0s 0us/step
[[[2692]
  [2715]
  [2702]]] [[2725.5286]]
1/1 [==============================] - 0s 0us/step
[[[2715]
  [2702]
  [2695]]] [[2731.6316]]
1/1 [==============================] - 0s 0us/step
[[[2702]
  [2695]
  [2620]]] [[2711.9531]]
1/1 [==============================] - 0s 0us/step
[[[2695]
  [2620]
  [2654]]] [[2686.3176]]
1/1 [==============================] - 0s 1ms/step
[[[2620]
  [2654]
  [2702]]] [[2666.9507]]
1/1 [==============================] - 0s 1ms/step
[[[2654]
  [2702]
  [2754]]] [[2708.7883]]
1/1 [==============================] - 0s 1000us/step
[[[2702]
  [2754]
  [2861]]] [[2766.932]]
1/1 [==============================] - 0s 2ms/step
[[[2754]
  [2861]
  [2853]]] [[2830.64]]
1/1 [==============================] - 0s 1ms/step
[[[2861]


[2723.9824,
 2697.178,
 2725.5286,
 2731.6316,
 2711.9531,
 2686.3176,
 2666.9507,
 2708.7883,
 2766.932,
 2830.64,
 2877.6113,
 2861.3608]