```
[Title] Cross Tabulation 
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents] 
 - Cross Tabulation(=Contingency Table) for WIP
```

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

df = pd.read_csv("../data_source/WIP_HISTORY.csv")

df1 = pysqldf("select GOOD_BAD, LINE, count(*) as FREQ from df group by GOOD_BAD, LINE ;")
df1


GOOD_BAD  LINE  FREQ
0         0     1  2968
1         0     2   659
2         0     3  3583
3         1     2  2466
4         1     3   324

In [3]:
pivotDf = df1.pivot(index='GOOD_BAD', columns='LINE')
pivotDf


FREQ                
LINE           1       2       3
GOOD_BAD                        
0         2968.0   659.0  3583.0
1            NaN  2466.0   324.0

In [4]:
matrix = pivotDf.values #dataframe -> numpy array
matrix

array([[2968.,  659., 3583.],
       [  nan, 2466.,  324.]])

In [5]:
matrix[1][0]=0
matrix

array([[2968.,  659., 3583.],
       [   0., 2466.,  324.]])

In [6]:
from scipy.stats import chi2_contingency
chisquare, p_value, dof, expected = chi2_contingency(matrix)
print('[Chisquare]', chisquare)
print('[p-value]', p_value)
print('[degree of freedom]', dof)
print('[expected]\n', expected)

[Chisquare] 5937.733917995892
[p-value] 0.0
[degree of freedom] 2
[expected]
 [[2139.928 2253.125 2816.947]
 [ 828.072  871.875 1090.053]]


In [31]:
(matrix-expected)

array([[  828.072, -1594.125,   766.053],
       [ -828.072,  1594.125,  -766.053]])

In [32]:
(matrix-expected)/expected

array([[ 0.38696255, -0.70751734,  0.27194441],
       [-1.        ,  1.8283871 , -0.70276675]])